backend:
  name: git-gateway
  branch: dev

media_folder: static/assets/uploads
public_folder: /assets/uploads

collections:
  - name: "blog"
    label: "Entrada de blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "doctors"
    label: "Doctors"
    folder: "content/doctors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "doctor"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Id", name: "title", widget: "string"}
      - {label: "Doctor's Image", name: "image", widget: "image"}
      - {label: "Specialty", name: "specialty", widget: "string"}

  - name: "videos"
    label: "Videos"
    folder: "content/videos"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "video"}
      - {label: "VideoName", name: "title", widget: "string"}
      - {label: "Video", name: "video", widget: "file"}
      - {label: "PublishDate", name: "date", widget: "datetime"}
      - {label: "Descripcion", name: "description", widget: "string"}

  - name: "faqs"
    label: "Frequently Asked Questions"
    folder: "content/faq"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
      - {label: "Question ID", name: "title", widget: "string"}
      - {label: "Question", name: "question", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "textContent"
    label: "Texto"
    folder: "content/textContent"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "faq"}
      - {label: "Content", name: "content", widget: "markdown"}